### ISSUE TITLE
post-processing volume reduction

### ISSUE THREAD

**Issue by NeuroDonu** [Eddycrack864/UVR5-UI#20]
hi, Eddy! i use your repo for separate my song. and after use, song has gotten quieter! I've used your repository before, but I didn't notice this - the volume stayed the same as when I started. maybe it's because of the model I'm using? I'm using melband roformer kim v2 by unwa (both tried), maybe it's only with them...?

**Comment by Eddycrack864** [comment]
Hi, thanks for using my UVR5 UI. I'm pretty sure the problem is due to the Amplification Threshold, it's a new feature added since version 1.6. To fix it you just need to increase the Amplification Threshold to make it louder.

The default value is 0.1, I recommend trying 0.5 or 0.6. Higher values ​​can introduce noise into the audio.
