### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by makhlwf** [Eddycrack864/UVR5-UI#4]
Hello, I want to run this locally on my computer. Can I just run the app.py? Or... This need more of changes. Or other files.

**Comment by aris-py** [comment]
For this we need the audio separator to work well but it has problems with gradio (I tried to do it and it didn't separate from the UI)

**Comment by Eddycrack864** [comment]
It's possible, after installing the requirements and running it through CMD, but there are likely to be errors. In the future I'll work on a local version if I find it feasible.

**Comment by aris-py** [comment]
UPDATE: It's soooo broken locally so it's impossible, UVR5 UI Local cancelled for now (I tried to fix it but I broke it more xd).

**Comment by Eddycrack864** [comment]
@makhlwf 
UPDATE: Now it's possible to run UVR5 UI locally on Windows or Linux. 

Just follow the installation steps:
https://github.com/Eddycrack864/UVR5-UI?tab=readme-ov-file#getting-started

**Comment by makhlwf** [comment]
It didn't work for me. I opened the installation script and it seems that everything installed probably. Then I opened the running script and it says that it's running on the local URL. And I copied the link and I opened it and nothing is there. And I don't know where the problem is. I just installed Python 13. Is this the problem? But I don't think so because I think it's running on virtual environment.

**Comment by Eddycrack864** [comment]
Are you running UVR5 UI on Linux? If so there seems to be a problem with certain Linux distributions. The problem is that the interface is not displayed in the browser, but everything works correctly without showing any errors or warnings on terminal.

I have the same problem on Ubuntu 24.04.1 but on Arch Linux it works. Because there are no errors or warnings it is more difficult to figure out what the problem is.

### As solution for now:
Use Gradio share links, this way your computer will act as a server, but you will need another device from which to open the link and make the audio separations. To enable share links add the `--share` parameter to the `run-UVR5-UI.sh` file like this:

```
env/bin/python app.py --share
```

Windows doesn't seem to have this problem. And yes, python 3.13 doesn't affect the installation because it uses an env.

I'll keep trying to find a solution to this problem.

**Comment by makhlwf** [comment]
Yeah, as you said, the problem seems difficult to know, because there are not any errors. But unfortunately, I'm using Windows. Can I still make a shareable link to try? I got my local URL, but when I'm trying to open it on the browser, nothing is displayed there.

**Comment by Eddycrack864** [comment]
Damn it! Even in Windows, ok that's not good. It's working pretty fine on my W11.

Anyways, yes you can make a shareable link adding --share on the run-UVR5.bat.

Also have u tried other browsers? And also u can try the fixes described in the troubleshooting file [here](https://github.com/Eddycrack864/UVR5-UI/blob/main/info/troubleshooting.md) maybe the dev mode or the UTF-8 encoding could work.

**Comment by makhlwf** [comment]
Yeah, I faced the UTF-8 problem and I tried the solution and it worked. 
I will try the dev mode also. And I will tell you. 
about the share argument. I think I know how to do it, but it's best to make sure that. So, do I need to add it in a new empty line or should I add it after a specific line in the file?

**Comment by Eddycrack864** [comment]
You need to add --share on line 11 in run-UVR5-UI.bat file.

This will be the complete code to run it with shareable links:

```
@echo off
setlocal
title UVR5 UI

if not exist env (
    echo Please run 'UVR5-UI-installer.bat' first to set up the environment
    pause
    exit /b 1
)

env\python.exe app.py --share
echo.
pause
```

Lmk if works

**Comment by makhlwf** [comment]
I have added the share argument now, and I took the link and opened it on my phone. I saw the loading screen and then empty black screen.

**Comment by makhlwf** [comment]
I've thought that the problem could be fixed if I run the updater file, but it gives this error.


```

fatal: detected dubious ownership in repository at 'C:/UVR5-UI'
'C:/UVR5-UI' is owned by:
        BUILTIN/Administrators (S-1-5-32-544)
but the current user is:
        MAKHLWF/altrh (S-1-5-21-3025980809-1343675554-2029725123-1001)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/UVR5-UI
fatal: detected dubious ownership in repository at 'C:/UVR5-UI'
'C:/UVR5-UI' is owned by:
        BUILTIN/Administrators (S-1-5-32-544)
but the current user is:
        MAKHLWF/altrh (S-1-5-21-3025980809-1343675554-2029725123-1001)
To add an exception for this directory, call:

        git config --global --add safe.directory C:/UVR5-UI
Update Complete!

Press any key to continue . . .

```

**Comment by Eddycrack864** [comment]
> I have added the share argument now, and I took the link and opened it on my phone. I saw the loading screen and then empty black screen.

No way! In my case I can access from my mobile and my other PC.

> Also there is this line at the beginning of the terminal window
> 
> ```
> INFO: Could not find files for the given pattern(s).
> ```

I also get that message in my Windows CMD but the program continues to work correctly, so it's nothing to worry about.

> I've thought that the problem could be fixed if I run the updater file, but it gives this error.
> 
> ```
> 
> fatal: detected dubious ownership in repository at 'C:/UVR5-UI'
> 'C:/UVR5-UI' is owned by:
>         BUILTIN/Administrators (S-1-5-32-544)
> but the current user is:
>         MAKHLWF/altrh (S-1-5-21-3025980809-1343675554-2029725123-1001)
> To add an exception for this directory, call:
> 
>         git config --global --add safe.directory C:/UVR5-UI
> fatal: detected dubious ownership in repository at 'C:/UVR5-UI'
> 'C:/UVR5-UI' is owned by:
>         BUILTIN/Administrators (S-1-5-32-544)
> but the current user is:
>         MAKHLWF/altrh (S-1-5-21-3025980809-1343675554-2029725123-1001)
> To add an exception for this directory, call:
> 
>         git config --global --add safe.directory C:/UVR5-UI
> Update Complete!
> 
> Press any key to continue . . .
> ```

That's git related. That error occurs due to a Git security measure related to repository directory ownership. Git is detecting that the directory 'C:/UVR5-UI' is owned by the group 'Administrators' but you are running Git under a different user ('MAKHLWF/altrh'), cause you are logged in git maybe cause u have made commits to some repo from git.
There are two ways to resolve this issue:

The easiest way is to run the command that Git suggests:
```
git config --global --add safe.directory C:/UVR5-UI
```
This command tells Git to trust this specific directory even though it has a different owner.

**Safer alternative:** Run the script as administrator (right click -> "Run as administrator")

But I don't think using the updater will work, since you will only get the latest changes from the repository, but I haven't made any changes yet to try to fix it.

Well, I'll start debugging the code to figure out what's going on. Sorry for the inconvenience, I hope to fix it soon.

**Comment by makhlwf** [comment]
Yeah, it worked perfectly now, and I had a success separation.

**Comment by makhlwf** [comment]
Issue is solved
